import type { Metadata } from "next";
import './globals.css';

import { VisualEditing } from 'next-sanity';
import { draftMode } from 'next/headers';

// import { SanityLive } from "@/sanity/lib/live";
import { DisableDraftMode } from '@/components/DisableDraftMode';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
        {/* <SanityLive /> */}
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
     
      </body>
    </html>
  );
}
